on:
  workflow_call:

jobs:
  release:
    name: Generate release notes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
